services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: jobtrack_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_vendor:/app/vendor
      - backend_var:/app/var
      - backend_public_bundles:/app/public/bundles
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: jobtrack_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
  backend_vendor:
  backend_var:
  backend_public_bundles: