<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260622121149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(255) NOT NULL, new_status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, application_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_48A559FE3E030ACD ON application_status_history (application_id)');
        $this->addSql('ALTER TABLE application_status_history ADD CONSTRAINT FK_48A559FE3E030ACD FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application_status_history DROP CONSTRAINT FK_48A559FE3E030ACD');
        $this->addSql('DROP TABLE application_status_history');
    }
}
